load("@build_stack_rules_proto//go:go_grpc_compile.bzl", "go_grpc_compile")

go_grpc_compile(
    name = "google_devtools_build_v1_publish_build_event_go_proto",
    has_services = True,
    #importpath = "github.com/example/project/src/proto",
    deps = [
        "@googleapis//:google_devtools_build_v1_publish_build_event_proto",
    ],
)
